# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171002_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='keyword',
        ),
    ]
