# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20171021_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(to='main_app.Card'),
        ),
    ]
